### ISSUE TITLE
Working directory expects settings but settings is defined afterwards

### ISSUE THREAD

**Issue by rhymes** [laurynas/sidekiq-pool#15]
So, according to the [readme](https://github.com/laurynas/sidekiq-pool#installation) the option "working_directory" in the yaml file is optional so I created a file "config/sidekiq-pool.yml" which looks like this:

```yaml
:workers:
  -
    :command: '-q high'
    :amount: 1
  -
    :command: '-q low'
    :amount: 1
```

Then I executed `bundle exec sidekiq-pool` and it broken with the following error:

```
2017-05-04T20:48:43.502Z 42965 TID-ouqupxxko INFO: Starting new pool
undefined method `[]' for nil:NilClass
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/sidekiq-pool-1.5.2/lib/sidekiq/pool/cli.rb:45:in `working_directory'
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/sidekiq-pool-1.5.2/lib/sidekiq/pool/cli.rb:50:in `start_new_pool'
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/sidekiq-pool-1.5.2/lib/sidekiq/pool/cli.rb:21:in `run'
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/sidekiq-pool-1.5.2/bin/sidekiq-pool:12:in `<top (required)>'
/Users/rhymes/.rvm/gems/ruby-2.3.4/bin/sidekiq-pool:22:in `load'
/Users/rhymes/.rvm/gems/ruby-2.3.4/bin/sidekiq-pool:22:in `<main>'
/Users/rhymes/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/Users/rhymes/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
````

I dug in the code a little bit and I think the problem is due to lines 50 and 51 in https://github.com/laurynas/sidekiq-pool/blob/master/lib/sidekiq/pool/cli.rb#L50

The statement `Dir.chdir(working_directory) if working_directory` calls the method working_directory on line 44 which, if there is no working directory defined as an instance variable tries to read it from the settings.

The issue is the settings object is created after that call, so the object `@settings` is nil and not an empty dictionary.

It was introduced with this commit: https://github.com/laurynas/sidekiq-pool/commit/ba4affbb4a6efa603c5ef78ab1030e21f9b7c38b

I think the easiest solution is to initialize `@settings = {}` in the initializer https://github.com/laurynas/sidekiq-pool/blob/master/lib/sidekiq/pool/cli.rb#L7

so that @settings[:working_directory] can return nil and the method can go on.

Unfortunately I wasn't able to find a way to make sidekiq pool start, even by specifying the working_directory directive, because it is parsed right after, as I said

Version 1.5.1 works fine.

**Comment by rhymes** [comment]
This is fixed by #14

**Comment by laurynas** [comment]
Merged a fix: https://github.com/laurynas/sidekiq-pool/pull/14

**Comment by rhymes** [comment]
Thanks!
