### ISSUE TITLE
/proc/{pid}/cmdline does not exist in OSX

### ISSUE THREAD

**Issue by rhymes** [laurynas/sidekiq-pool#16]
I understand sidekiq-pool is meant to run on a server and servers are mainly Linux machines so you have access to the /proc folder but lots of devs (or at least I do) use OSX to code and test.

I tried to execute "bundle exec sidekiq-pool" to test the configuration but I do have an issue with https://github.com/laurynas/sidekiq-pool/blob/master/lib/sidekiq/pool/cli.rb#L276 where the method `def cmdline_busy?(pid)` tries to read the cmdline of the pid from such folder, which then breaks in OSX:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /proc/44401/cmdline
```

This exception should probably be rescued.

**Comment by laurynas** [comment]
Added a check of `cmdline` existence: https://github.com/laurynas/sidekiq-pool/commit/6a9d1b553465f242633584a9757cdb61276e9a1f
