### ISSUE TITLE
Sidekiq 5

### ISSUE THREAD

**Issue by rhymes** [laurynas/sidekiq-pool#17]
This gem is locked on Sidekiq 4, but it should work as is with Sidekiq 5:

- changelog: https://github.com/mperham/sidekiq/blob/master/Changes.md
- upgrade guide: https://github.com/mperham/sidekiq/blob/master/5.0-Upgrade.md

**Comment by rhymes** [comment]
See PR #18

**Comment by laurynas** [comment]
@rhymes thanks, I will check it. sorry for delay

**Comment by laurynas** [comment]
Merged PR https://github.com/laurynas/sidekiq-pool/pull/18 and released `1.5.4` version.

**Comment by rhymes** [comment]
@laurynas thank you! :-)
