### ISSUE TITLE
Sidekiq 5.1

### ISSUE THREAD

**Issue by rhymes** [laurynas/sidekiq-pool#21]
This gem is locked on Sidekiq < 5.1, but it should work as is with Sidekiq 5.1 as well:

- changelog: https://github.com/mperham/sidekiq/blob/master/Changes.md

**Comment by kigster** [comment]
Any particular reason it is frozen to Sidekiq > version 4? We are still on 3 and I think the gem will work as is.

**Comment by laurynas** [comment]
Thanks for reporting! Added Sidekiq 5.1 and Sidekiq 3 support, released [1.7.0 version](https://rubygems.org/gems/sidekiq-pool).
